redis_backup_dir: /tmp/redis-backup
redis_backup_azure_container_name: redis-backup
learner_user: learning
redis_data_dir: /data
redis_version: 6.2.5
redis_dir: "/home/{{ learner_user }}/redis-{{ redis_version }}"
