- hosts: learningall
  become: yes
  vars:
    learnings:
      paths: ['/data', '/data/graphDB', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform']
      service_config: ['consumer-config.xml']
    searchs:
      paths: ['/data', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform', '/home/learning/platform/search', '/home/learning/platform/service', '/home/learning/platform/service/logs' ]
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  pre_tasks:
    - name: Create learner group
      become: yes
      group:
        state: present
        name: "{{ learner_group }}"
        system: yes
    - name: Create learner user
      become: yes
      user:
        state: present
        name: "{{ learner_user }}"
        comment: learner user
        system: yes
        createhome: yes
        group: "{{ learner_group }}"
    - name: create folder data for learning
      become: yes
      file: path={{ item }} state=directory mode=0775 owner={{learner_user}} group={{learner_user}}
      with_items: "{{ learnings.paths }}"
  roles:
    - jdk-1.8.0_121
    - jdk11
    - tomcat
    - ffmpeg
    - imagemagick
    - logstash
