- hosts: redisall
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  pre_tasks:
    - name: Create learner group
      become: yes
      group:
        state: present
        name: "{{ learner_group }}"
        system: yes
    - name: Create learner user
      become: yes
      user:
        state: present
        name: "{{ learner_user }}"
        comment: learner user
        system: yes
        createhome: yes
        group: "{{ learner_group }}"
    - name: Install dependencies to build redis
      become: yes
      apt:
        name: build-essential
        state: installed
        update_cache: yes
  roles:
    - redis
  serial: 1
