- hosts: learning-neo4j-cluster
  vars:
    neo4j_dir: neo4j-learning
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: Check if neo4j is running
      become_user: "{{ learner_user }}"
      shell: ps -ef | grep "{{ neo4j_home }}"  | grep -v grep | wc -l
      register: neo4j_process

    - name: Start neo4j
      become: yes
      become_user: "{{ learner_user }}"
      shell:  bin/neo4j start
      args:
        chdir: "{{ neo4j_home }}"
      when: "neo4j_process.stdout == '0'"
  serial: 1