- hosts: learningall
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{sunbird_artifact_storage_account_name}}"
    AZURE_STORAGE_KEY: "{{sunbird_artifact_storage_account_key}}"
  become: yes
  become_user: "{{learner_user}}"
  roles:      
    - neo4j-es-sync-tool
  run_once: true
